CREATE TABLE starwars (
    `id` INT,
    `name` VARCHAR(14) CHARACTER SET utf8,
    `height` INT,
    `mass` INT,
    `hairColor` VARCHAR(5) CHARACTER SET utf8,
    `skinColor` VARCHAR(4) CHARACTER SET utf8,
    `eyeColor` VARCHAR(4) CHARACTER SET utf8,
    `birthYear` VARCHAR(5) CHARACTER SET utf8,
    `gender` VARCHAR(4) CHARACTER SET utf8,
    `homeworld_name` VARCHAR(8) CHARACTER SET utf8,
    `homeworld_rotationPeriod` INT,
    `homeworld_orbitalPeriod` INT,
    `homeworld_diameter` INT,
    `homeworld_climate` VARCHAR(4) CHARACTER SET utf8,
    `homeworld_gravity` VARCHAR(10) CHARACTER SET utf8,
    `homeworld_terrain` VARCHAR(6) CHARACTER SET utf8,
    `homeworld_surfaceWater` INT,
    `homeworld_population` INT,
    `starships_name` VARCHAR(16) CHARACTER SET utf8,
    `starships_model` VARCHAR(25) CHARACTER SET utf8,
    `starships_manufacturer` VARCHAR(20) CHARACTER SET utf8,
    `starships_costInCredits` INT,
    `starships_length` NUMERIC(3, 1),
    `starships_maxAtmosphericSpeed` INT,
    `starships_crew` INT,
    `starships_passengers` INT,
    `starships_cargoCapacity` INT,
    `starships_consumables` VARCHAR(8) CHARACTER SET utf8,
    `starships_hyperdriveRating` NUMERIC(2, 1),
    `starships_mglt` INT,
    `starships_starshipClass` VARCHAR(26) CHARACTER SET utf8
);
INSERT INTO starwars VALUES
    (1,'Luke Skywalker',172,77,'blond','fair','blue','19BBY','male','Tatooine',23,304,10465,'arid','1 standard','desert',1,200000,'X-wing','T-65 X-wing','Incom Corporation',149999,12.5,1050,1,0,110,'1 week',1.0,100,'Starfighter'),
    (1,'Luke Skywalker',172,77,'blond','fair','blue','19BBY','male','Tatooine',23,304,10465,'arid','1 standard','desert',1,200000,'Imperial shuttle','Lambda-class T-4a shuttle','Sienar Fleet Systems',240000,20,850,6,20,80000,'2 months',1.0,50,'Armed government transport');
